<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabAnalyzerConnector.Communication\LabAnalyzerConnector.Communication.csproj" />
    <ProjectReference Include="..\LabAnalyzerConnector.Core\LabAnalyzerConnector.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>

</Project>
