// <auto-generated />
using System;
using LabAnalyzerConnector.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabAnalyzerConnector.Infrastructure.Migrations
{
    [DbContext(typeof(LabAnalyzerDbContext))]
    partial class LabAnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("LabAnalyzerConnector.Infrastructure.Persistence.Entities.AnalyzerConfigurationEntity", b =>
                {
                    b.Property<Guid>("AnalyzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoConnect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoReconnect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableErrorLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableParsedMessageLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRawMessageLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MappingProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxReconnectAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReconnectDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcpJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AnalyzerId");

                    b.HasIndex("AnalyzerId")
                        .IsUnique();

                    b.ToTable("AnalyzerConfigurations");
                });

            modelBuilder.Entity("LabAnalyzerConnector.Infrastructure.Persistence.Entities.AnalyzerMappingProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalyzerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzerId")
                        .IsUnique();

                    b.ToTable("AnalyzerMappingProfiles");
                });

            modelBuilder.Entity("LabAnalyzerConnector.Infrastructure.Persistence.Entities.LabResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbnormalFlag")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalyzerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResultDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardTestCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzerId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SampleId");

                    b.HasIndex("StandardTestCode");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("LabAnalyzerConnector.Infrastructure.Persistence.Entities.TestCodeMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalyzerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerTestCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalyzerTestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedUnit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardTestCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardTestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardUnit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzerId");

                    b.HasIndex("AnalyzerId", "AnalyzerTestCode")
                        .IsUnique();

                    b.ToTable("TestCodeMappings");
                });

            modelBuilder.Entity("LabAnalyzerConnector.Infrastructure.Persistence.LabOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnalyzerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderedTests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecimenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzerId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecimenId");

                    b.ToTable("LabOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
