<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\CBC_Normal.astm" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\CBC_Normal.astm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Resources\" />
    <Folder Include="Views\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabAnalyzerConnector.Application\LabAnalyzerConnector.Application.csproj" />
    <ProjectReference Include="..\LabAnalyzerConnector.Communication\LabAnalyzerConnector.Communication.csproj" />
    <ProjectReference Include="..\LabAnalyzerConnector.Core\LabAnalyzerConnector.Core.csproj" />
    <ProjectReference Include="..\LabAnalyzerConnector.Protocols\LabAnalyzerConnector.Protocols.csproj" />
  </ItemGroup>

</Project>
